/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package digitalBankSystem;

import java.awt.HeadlessException;
import java.awt.event.KeyEvent;
import java.sql.*;

/**
 *
 * @author admin
 */
public class DEPOSIT extends javax.swing.JFrame {

    /**
     * Creates new form DEPOSIT
     */
    public DEPOSIT() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/digitalBankSystem/DEPOSIT.jpg"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/digitalBankSystem/wrong.png"))); // NOI18N
        jLabel4.setText("jLabel4");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 20, 25, -1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("DEPOSIT");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 100, -1, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Enter the amount");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 230, 240, 40));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Rs :");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 290, 60, 40));

        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField1KeyPressed(evt);
            }
        });
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 290, 180, 40));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton1.setText("EXIT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 410, -1, -1));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton2.setText("CLEAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 410, -1, -1));

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton3.setText("OK");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 410, 90, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/digitalBankSystem/depositnew.jpg"))); // NOI18N
        jLabel7.setText("jLabel7");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
        new LOGIN_BUTTONS().setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new WELCOME_TO_CSE_BANK().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        try{
            if (jTextField1.getText().equals(""))
            {
                javax.swing.JOptionPane.showMessageDialog(null, "PLEASE ENTER AMOUNT");
            }
            else
            {
                Class.forName("oracle.jdbc.driver.OracleDriver");
                Connection con = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:xe", "system", "system");
                String Query = "SELECT ACCOUNTNO FROM DBS.RECORD";
                java.sql.Statement ps=con.createStatement();
                java.sql.ResultSet rs= ps.executeQuery(Query);
                if(rs.next())
                {
                    long acc=Long.parseLong(rs.getString("ACCOUNTNO"));
                    double bal1= Double.parseDouble(jTextField1.getText());
                    String Query1 = "SELECT BALANCE FROM DBS.BALANCE WHERE ACCOUNTNO=?";
                    java.sql.PreparedStatement ps1 = con.prepareStatement(Query1);
                    ps1.setLong(1,acc);
                    java.sql.ResultSet rs1= ps1.executeQuery();
                    if(rs1.next())
                    {
                        double bal2=Double.parseDouble(rs1.getString("BALANCE"));
                        double bal =bal1+bal2;
                        String Query2="UPDATE DBS.BALANCE SET BALANCE=? WHERE ACCOUNTNO=?";
                        java.sql.PreparedStatement ps2 = con.prepareStatement(Query2);
                        ps2.setDouble(1,bal);
                        ps2.setLong(2,acc);
                        ps2.executeUpdate();
                        String Query3="SELECT TRANSACTIONID FROM DBS.TRANSACTION WHERE TRANSACTIONTYPE = ?";
                        java.sql.PreparedStatement ps3=con.prepareStatement(Query3);
                        ps3.setString(1,"DEFAULT");
                        java.sql.ResultSet rs3= ps3.executeQuery();
                        if(rs3.next())
                        {
                            long tid = Long.parseLong(rs3.getString("TRANSACTIONID"));
                            long tid1=tid+1;
                            String Query4 = "DELETE FROM DBS.TRANSACTION WHERE TRANSACTIONID=?";
                            java.sql.PreparedStatement ps4=con.prepareStatement(Query4);
                            ps4.setLong(1,tid);
                            ps4.executeUpdate();
                            double ba=Double.parseDouble(jTextField1.getText());
                            String Query5="INSERT INTO DBS.TRANSACTION(TRANSACTIONID,ACCOUNTNO,TRANSACTIONTYPE,TRANSFEREDTO,AMOUNT)VALUES(?,?,?,?,?)";
                            java.sql.PreparedStatement ps5=con.prepareStatement(Query5);
                            ps5.setLong(1,Long.parseLong(rs3.getString("TRANSACTIONID")));
                            ps5.setLong(2,Long.parseLong(rs.getString("ACCOUNTNO")));
                            ps5.setString(3,"DEPOSIT");
                            ps5.setString(4,"SELF_ACC");
                            ps5.setDouble(5,ba);
                            ps5.executeUpdate();
                            String Query6="INSERT INTO DBS.TRANSACTION(TRANSACTIONID,TRANSACTIONTYPE)VALUES(?,?)";
                            java.sql.PreparedStatement ps6=con.prepareStatement(Query6);
                            ps6.setLong(1,tid1);
                            ps6.setString(2,"DEFAULT");
                            ps6.executeUpdate();
                             javax.swing.JOptionPane.showMessageDialog(null, "Deposited successfully");
                            new LOGIN_BUTTONS().setVisible(true);
                            dispose();
                        }
                    }

                }
            }
        }
        catch(Exception e)
        {
            System.out.println(e);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTextField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode()==KeyEvent.VK_ENTER){
            try{
                if (jTextField1.getText().equals(""))
                {
                    javax.swing.JOptionPane.showMessageDialog(null, "PLEASE ENTER AMOUNT");
                }
                else
                {
                    Class.forName("oracle.jdbc.driver.OracleDriver");
                    Connection con = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:xe", "system", "system");
                    String Query = "SELECT ACCOUNTNO FROM DBS.RECORD";
                    java.sql.Statement ps=con.createStatement();
                    java.sql.ResultSet rs= ps.executeQuery(Query);
                    if(rs.next())
                    {
                        long acc=Long.parseLong(rs.getString("ACCOUNTNO"));
                        double bal1= Double.parseDouble(jTextField1.getText());
                        String Query1 = "SELECT BALANCE FROM DBS.BALANCE WHERE ACCOUNTNO=?";
                        java.sql.PreparedStatement ps1 = con.prepareStatement(Query1);
                        ps1.setLong(1,acc);
                        java.sql.ResultSet rs1= ps1.executeQuery();
                        if(rs1.next())
                        {
                            double bal2=Double.parseDouble(rs1.getString("BALANCE"));
                            double bal =bal1+bal2;
                            String Query2="UPDATE DBS.BALANCE SET BALANCE=? WHERE ACCOUNTNO=?";
                            java.sql.PreparedStatement ps2 = con.prepareStatement(Query2);
                            ps2.setDouble(1,bal);
                            ps2.setLong(2,acc);
                            ps2.executeUpdate();
                            String Query3="SELECT TRANSACTIONID FROM DBS.TRANSACTION WHERE TRANSACTIONTYPE = ?";
                            java.sql.PreparedStatement ps3=con.prepareStatement(Query3);
                            ps3.setString(1,"DEFAULT");
                            java.sql.ResultSet rs3= ps3.executeQuery();
                            if(rs3.next())
                            {
                                long tid = Long.parseLong(rs3.getString("TRANSACTIONID"));
                                long tid1=tid+1;
                                String Query4 = "DELETE FROM DBS.TRANSACTION WHERE TRANSACTIONID=?";
                                java.sql.PreparedStatement ps4=con.prepareStatement(Query4);
                                ps4.setLong(1,tid);
                                ps4.executeUpdate();
                                double ba=Double.parseDouble(jTextField1.getText());
                                String Query5="INSERT INTO DBS.TRANSACTION(TRANSACTIONID,ACCOUNTNO,TRANSACTIONTYPE,TRANSFEREDTO,AMOUNT)VALUES(?,?,?,?,?)";
                                java.sql.PreparedStatement ps5=con.prepareStatement(Query5);
                                ps5.setLong(1,Long.parseLong(rs3.getString("TRANSACTIONID")));
                                ps5.setLong(2,Long.parseLong(rs.getString("ACCOUNTNO")));
                                ps5.setString(3,"DEPOSIT");
                                ps5.setString(4,"SELF_ACC");
                                ps5.setDouble(5,ba);
                                ps5.executeUpdate();
                                String Query6="INSERT INTO DBS.TRANSACTION(TRANSACTIONID,TRANSACTIONTYPE)VALUES(?,?)";
                                java.sql.PreparedStatement ps6=con.prepareStatement(Query6);
                                ps6.setLong(1,tid1);
                                ps6.setString(2,"DEFAULT");
                                ps6.executeUpdate();
                                 javax.swing.JOptionPane.showMessageDialog(null, "Deposited successfully");
                                new LOGIN_BUTTONS().setVisible(true);
                                dispose();
                            }
                        }

                    }
                }
            }
           catch(Exception e)
            {
                System.out.println(e);
            }
        }
    }//GEN-LAST:event_jTextField1KeyPressed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        jTextField1.setText(null);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DEPOSIT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DEPOSIT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DEPOSIT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DEPOSIT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DEPOSIT().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
