package digitalBankSystem;

import java.awt.event.KeyEvent;
import java.sql.*;
import java.sql.PreparedStatement;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author admin
 */
public class INSERT extends javax.swing.JFrame {

    /**
     * Creates new form INSERT
     */
    public INSERT() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField3 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        jTextField3.setText("jTextField3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/digitalBankSystem/wrong.png"))); // NOI18N
        jLabel6.setText("jLabel6");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 10, 25, -1));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jButton1.setText("EXIT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 500, -1, -1));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jButton2.setText("CLEAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 500, -1, -1));

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jButton3.setText("CREATE");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 500, -1, -1));

        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField1KeyPressed(evt);
            }
        });
        jPanel2.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 200, 230, -1));

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jTextField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField2KeyPressed(evt);
            }
        });
        jPanel2.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 260, 230, -1));

        jTextField4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField4KeyPressed(evt);
            }
        });
        jPanel2.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 380, 230, -1));

        jTextField5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField5KeyPressed(evt);
            }
        });
        jPanel2.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 320, 230, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/digitalBankSystem/CREATEACCOUNT.jpg"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
        new ADMINISTRATOR_MAIN().setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        try
        {
            if (jTextField1.getText().equals(""))
            {
                javax.swing.JOptionPane.showMessageDialog(null, "PLEASE FILL CREDENTIALS");
            }
            else if (jTextField2.getText().equals(""))
            {
                javax.swing.JOptionPane.showMessageDialog(null, "PLEASE FILL CREDENTIALS");
            }
            else if (jTextField4.getText().equals(""))
            {
                javax.swing.JOptionPane.showMessageDialog(null, "PLEASE FILL CREDENTIALS");
            }
            else
            {
                Class.forName("oracle.jdbc.driver.OracleDriver");
                Connection con = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:xe", "system", "system");
                String Query="SELECT ACCOUNTNO FROM DBS.ACCOUNTS WHERE USERNAME=?";
                PreparedStatement ps=con.prepareStatement(Query);
                ps.setString(1,"DEFAULT");
                ResultSet rs= ps.executeQuery();
                if(rs.next())
                {
                    long acc=Long.parseLong(rs.getString("ACCOUNTNO"));
                    long acc1=acc+1;
                    double bal=Double.parseDouble(jTextField4.getText());
                    String q1="DELETE FROM DBS.ACCOUNTS WHERE ACCOUNTNO=?";
                    PreparedStatement pstmt=con.prepareStatement(q1);
                    pstmt.setLong(1,Long.parseLong(rs.getString("ACCOUNTNO")));
                    pstmt.executeUpdate();
                    String Query1="INSERT INTO DBS.ACCOUNTS(ACCOUNTNO,USERNAME,MOBILENO,AADHARNO) VALUES(?,?,?,?)";
                    String Query2="INSERT INTO DBS.BALANCE VALUES(?,?)";
                    String Query3="INSERT INTO DBS.ACCOUNTS(ACCOUNTNO,USERNAME) VALUES(?,?)";
                    java.sql.PreparedStatement ps1=con.prepareStatement(Query1);
                    ps1.setLong(1,Long.parseLong(rs.getString("ACCOUNTNO")));
                    ps1.setString(2,jTextField1.getText());
                    ps1.setLong(3,Long.parseLong(jTextField2.getText()));
                    ps1.setLong(4,Long.parseLong(jTextField4.getText()));
                    java.sql.PreparedStatement ps2=con.prepareStatement(Query2);
                    ps2.setLong(1,Long.parseLong(rs.getString("ACCOUNTNO")));
                    ps2.setDouble(2,Double.parseDouble(jTextField4.getText()));
                    java.sql.PreparedStatement ps3=con.prepareStatement(Query3);
                    ps3.setLong(1,acc1);
                    ps3.setString(2,"DEFAULT");
                    if(jTextField1.getText().equals(""))
                    {
                        javax.swing.JOptionPane.showMessageDialog(null, "PLEASE FILL CREDENTIALS");
                    }
                    else if (jTextField2.getText().equals(""))
                    {
                        javax.swing.JOptionPane.showMessageDialog(null, "PLEASE FILL CREDENTIALS");
                    }
                    else if (jTextField4.getText().equals(""))
                    {
                        javax.swing.JOptionPane.showMessageDialog(null, "PLEASE FILL CREDENTIALS");
                    }
                    else if(bal<500)
                    {
                        javax.swing.JOptionPane.showMessageDialog(null, "INTIAL BALANCE SHOULD BE MINIMUM 500Rs.");
                    }
                    else
                    {
                        ps1.executeUpdate();
                        ps2.executeUpdate();
                        ps3.executeUpdate();
                        javax.swing.JOptionPane.showMessageDialog(null, "ACCOUNT IS CREATED SUCESSFULLY");
                        new ADMINISTRATOR_MAIN().setVisible(true);
                        dispose();
                    }
                }
                else
                {
                    javax.swing.JOptionPane.showMessageDialog(null, "ACCOUNT  CAN'T BE CREATED");
                }
            }

        }
        catch(Exception e)
        {
            System.out.println(e);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        jTextField1.setText(null);
        jTextField2.setText(null);
        jTextField4.setText(null);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new WELCOME_TO_CSE_BANK().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField4KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField4KeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode()==KeyEvent.VK_ENTER){
            try
            {
                if (jTextField1.getText().equals(""))
                {
                    javax.swing.JOptionPane.showMessageDialog(null, "PLEASE FILL CREDENTIALS");
                }
                else if (jTextField2.getText().equals(""))
                {
                    javax.swing.JOptionPane.showMessageDialog(null, "PLEASE FILL CREDENTIALS");
                }
                else if (jTextField4.getText().equals(""))
                {
                    javax.swing.JOptionPane.showMessageDialog(null, "PLEASE FILL CREDENTIALS");
                }
                else
                {
                    Class.forName("oracle.jdbc.driver.OracleDriver");
                    Connection con = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:xe", "system", "system");
                    String Query="SELECT ACCOUNTNO FROM DBS.ACCOUNTS WHERE USERNAME=?";
                    PreparedStatement ps=con.prepareStatement(Query);
                    ps.setString(1,"DEFAULT");
                    ResultSet rs= ps.executeQuery();
                    if(rs.next())
                    {
                        long acc=Long.parseLong(rs.getString("ACCOUNTNO"));
                        long acc1=acc+1;
                        double bal=Double.parseDouble(jTextField4.getText());
                        String q1="DELETE FROM DBS.ACCOUNTS WHERE ACCOUNTNO=?";
                        PreparedStatement pstmt=con.prepareStatement(q1);
                        pstmt.setLong(1,Long.parseLong(rs.getString("ACCOUNTNO")));
                        pstmt.executeUpdate();
                        String Query1="INSERT INTO DBS.ACCOUNTS(ACCOUNTNO,USERNAME,MOBILENO) VALUES(?,?,?)";
                        String Query2="INSERT INTO DBS.BALANCE VALUES(?,?)";
                        String Query3="INSERT INTO DBS.ACCOUNTS(ACCOUNTNO,USERNAME) VALUES(?,?)";
                        java.sql.PreparedStatement ps1=con.prepareStatement(Query1);
                        ps1.setLong(1,Long.parseLong(rs.getString("ACCOUNTNO")));
                        ps1.setString(2,jTextField1.getText());
                        ps1.setLong(3,Long.parseLong(jTextField2.getText()));
                        java.sql.PreparedStatement ps2=con.prepareStatement(Query2);
                        ps2.setLong(1,Long.parseLong(rs.getString("ACCOUNTNO")));
                        ps2.setDouble(2,Double.parseDouble(jTextField4.getText()));
                        java.sql.PreparedStatement ps3=con.prepareStatement(Query3);
                        ps3.setLong(1,acc1);
                        ps3.setString(2,"DEFAULT");
                        if(jTextField1.getText().equals(""))
                        {
                            javax.swing.JOptionPane.showMessageDialog(null, "PLEASE FILL CREDENTIALS");
                        }
                        else if (jTextField2.getText().equals(""))
                        {
                            javax.swing.JOptionPane.showMessageDialog(null, "PLEASE FILL CREDENTIALS");
                        }
                        else if (jTextField4.getText().equals(""))
                        {
                            javax.swing.JOptionPane.showMessageDialog(null, "PLEASE FILL CREDENTIALS");
                        }
                        else if(bal<500)
                        {
                            javax.swing.JOptionPane.showMessageDialog(null, "INTIAL BALANCE SHOULD BE MINIMUM 500Rs.");
                        }
                        else
                        {
                            ps1.executeUpdate();
                            ps2.executeUpdate();
                            ps3.executeUpdate();
                            javax.swing.JOptionPane.showMessageDialog(null, "ACCOUNT IS CREATED SUCESSFULLY");
                            new ADMINISTRATOR_MAIN().setVisible(true);
                            dispose();
                        }
                    }
                    else
                    {
                        javax.swing.JOptionPane.showMessageDialog(null, "ACCOUNT  CAN'T BE CREATED");
                    }
                }

            }
            catch(Exception e)
            {
                System.out.println(e);
            }
        }
    }//GEN-LAST:event_jTextField4KeyPressed

    private void jTextField2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField2KeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode()==KeyEvent.VK_ENTER)
        jTextField5.requestFocus();
    }//GEN-LAST:event_jTextField2KeyPressed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode()==KeyEvent.VK_ENTER)
        jTextField2.requestFocus();
    }//GEN-LAST:event_jTextField1KeyPressed

    private void jTextField5KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField5KeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode()==KeyEvent.VK_ENTER)
        jTextField4.requestFocus();
    }//GEN-LAST:event_jTextField5KeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(INSERT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(INSERT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(INSERT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(INSERT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new INSERT().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables
}
